spring.application.name=person-back
spring.datasource.url=jdbc:mysql://localhost:3306/persons?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=deadStalker!0140dbM

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8093
